package com.model;

import java.sql.Timestamp;

/**
 * TFenshu generated by MyEclipse Persistence Tools
 */

public class TFenshu implements java.io.Serializable
{

	// Fields

	private Integer fenshuId;

	private Integer shitiId;
	
	private int stuId;

	private Integer fenshu;
	
	private String stuRealName;
	private String shitiName;

	private Timestamp yuejuanDate;
	
	private Integer teaId;
	
	// Constructors

	/** default constructor */
	public TFenshu()
	{
	}

	/** full constructor */
	public TFenshu(Integer shitiId, Integer fenshu)
	{
		this.shitiId = shitiId;
		this.fenshu = fenshu;
	}

	// Property accessors

	public Integer getFenshuId()
	{
		return this.fenshuId;
	}

	public void setFenshuId(Integer fenshuId)
	{
		this.fenshuId = fenshuId;
	}

	public String getShitiName()
	{
		return shitiName;
	}

	public void setShitiName(String shitiName)
	{
		this.shitiName = shitiName;
	}

	public String getStuRealName()
	{
		return stuRealName;
	}

	public void setStuRealName(String stuRealName)
	{
		this.stuRealName = stuRealName;
	}

	public Integer getShitiId()
	{
		return this.shitiId;
	}

	public void setShitiId(Integer shitiId)
	{
		this.shitiId = shitiId;
	}

	public Integer getFenshu()
	{
		return this.fenshu;
	}

	public void setFenshu(Integer fenshu)
	{
		this.fenshu = fenshu;
	}

	public int getStuId()
	{
		return stuId;
	}

	public void setStuId(int stuId)
	{
		this.stuId = stuId;
	}

	public Timestamp getYuejuanDate() {
		return yuejuanDate;
	}

	public void setYuejuanDate(Timestamp yuejuanDate) {
		this.yuejuanDate = yuejuanDate;
	}

	public Integer getTeaId() {
		return teaId;
	}

	public void setTeaId(Integer teaId) {
		this.teaId = teaId;
	}
	
	

}