package com.model;

/**
 * TKecheng generated by MyEclipse Persistence Tools
 */

public class TKecheng implements java.io.Serializable
{

	// Fields

	private Integer kechengId;

	private String kechengBianhao;

	private String kechengName;

	private String kechengXueshi;

	private String del;

	// Constructors

	/** default constructor */
	public TKecheng()
	{
	}

	/** minimal constructor */
	public TKecheng(String del)
	{
		this.del = del;
	}

	/** full constructor */
	public TKecheng(String kechengBianhao, String kechengName,
			String kechengXueshi, String del)
	{
		this.kechengBianhao = kechengBianhao;
		this.kechengName = kechengName;
		this.kechengXueshi = kechengXueshi;
		this.del = del;
	}

	// Property accessors

	public Integer getKechengId()
	{
		return this.kechengId;
	}

	public void setKechengId(Integer kechengId)
	{
		this.kechengId = kechengId;
	}

	public String getKechengBianhao()
	{
		return this.kechengBianhao;
	}

	public void setKechengBianhao(String kechengBianhao)
	{
		this.kechengBianhao = kechengBianhao;
	}

	public String getKechengName()
	{
		return this.kechengName;
	}

	public void setKechengName(String kechengName)
	{
		this.kechengName = kechengName;
	}

	public String getKechengXueshi()
	{
		return this.kechengXueshi;
	}

	public void setKechengXueshi(String kechengXueshi)
	{
		this.kechengXueshi = kechengXueshi;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}