package com.model;

/**
 * TStu generated by MyEclipse Persistence Tools
 */

public class TStu implements java.io.Serializable
{

	// Fields

	private Integer stuId;

	private String stuXuehao;

	private String stuRealname;

	private String stuSex;

	private String stuAge;

	private String stuXueyuan;

	private String stuZhuanye;

	private String stuBanji;

	private String loginPw;

	private String del;

	// Constructors

	/** default constructor */
	public TStu()
	{
	}

	/** full constructor */
	public TStu(String stuXuehao, String stuRealname, String stuSex,
			String stuAge, String stuXueyuan, String stuZhuanye,
			String stuBanji, String loginPw, String del)
	{
		this.stuXuehao = stuXuehao;
		this.stuRealname = stuRealname;
		this.stuSex = stuSex;
		this.stuAge = stuAge;
		this.stuXueyuan = stuXueyuan;
		this.stuZhuanye = stuZhuanye;
		this.stuBanji = stuBanji;
		this.loginPw = loginPw;
		this.del = del;
	}

	// Property accessors

	public Integer getStuId()
	{
		return this.stuId;
	}

	public void setStuId(Integer stuId)
	{
		this.stuId = stuId;
	}

	public String getStuXuehao()
	{
		return this.stuXuehao;
	}

	public void setStuXuehao(String stuXuehao)
	{
		this.stuXuehao = stuXuehao;
	}

	public String getStuRealname()
	{
		return this.stuRealname;
	}

	public void setStuRealname(String stuRealname)
	{
		this.stuRealname = stuRealname;
	}

	public String getStuSex()
	{
		return this.stuSex;
	}

	public void setStuSex(String stuSex)
	{
		this.stuSex = stuSex;
	}

	public String getStuAge()
	{
		return this.stuAge;
	}

	public void setStuAge(String stuAge)
	{
		this.stuAge = stuAge;
	}


	public String getStuXueyuan() {
		return stuXueyuan;
	}

	public void setStuXueyuan(String stuXueyuan) {
		this.stuXueyuan = stuXueyuan;
	}

	public String getStuZhuanye() {
		return stuZhuanye;
	}

	public void setStuZhuanye(String stuZhuanye) {
		this.stuZhuanye = stuZhuanye;
	}

	public String getStuBanji() {
		return stuBanji;
	}

	public void setStuBanji(String stuBanji) {
		this.stuBanji = stuBanji;
	}

	public String getLoginPw()
	{
		return this.loginPw;
	}

	public void setLoginPw(String loginPw)
	{
		this.loginPw = loginPw;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}