package com.model;

/**
 * TTimu generated by MyEclipse Persistence Tools
 */

public class TTimu implements java.io.Serializable
{

	// Fields

	private Integer timuId;

	private String timuName;

	private String timuLeixing;

	private String timuXuanxianga;

	private String timuXuanxiangb;

	private String timuXuanxiangc;

	private String timuXuanxiangd;

	private String timuDaan;

	private Integer timuFenshu;
	
	private Integer kechengId;
	
	private Integer timuNandu;
	
	private String del;
	
	private String timuDaanAsStu;//学生的答案。数据库没有此字段

	// Constructors

	/** default constructor */
	public TTimu()
	{
	}


	// Property accessors

	public Integer getTimuId()
	{
		return this.timuId;
	}

	public void setTimuId(Integer timuId)
	{
		this.timuId = timuId;
	}

	public String getTimuDaanAsStu()
	{
		return timuDaanAsStu;
	}

	public void setTimuDaanAsStu(String timuDaanAsStu)
	{
		this.timuDaanAsStu = timuDaanAsStu;
	}

	public String getTimuName()
	{
		return this.timuName;
	}

	public void setTimuName(String timuName)
	{
		this.timuName = timuName;
	}

	public String getTimuLeixing()
	{
		return this.timuLeixing;
	}

	public Integer getTimuFenshu()
	{
		return timuFenshu;
	}

	public void setTimuFenshu(Integer timuFenshu)
	{
		this.timuFenshu = timuFenshu;
	}

	public void setTimuLeixing(String timuLeixing)
	{
		this.timuLeixing = timuLeixing;
	}

	public String getTimuXuanxianga()
	{
		return this.timuXuanxianga;
	}

	public void setTimuXuanxianga(String timuXuanxianga)
	{
		this.timuXuanxianga = timuXuanxianga;
	}

	public String getTimuXuanxiangb()
	{
		return this.timuXuanxiangb;
	}

	public void setTimuXuanxiangb(String timuXuanxiangb)
	{
		this.timuXuanxiangb = timuXuanxiangb;
	}

	public String getTimuXuanxiangc()
	{
		return this.timuXuanxiangc;
	}

	public void setTimuXuanxiangc(String timuXuanxiangc)
	{
		this.timuXuanxiangc = timuXuanxiangc;
	}

	public String getTimuXuanxiangd()
	{
		return this.timuXuanxiangd;
	}

	public void setTimuXuanxiangd(String timuXuanxiangd)
	{
		this.timuXuanxiangd = timuXuanxiangd;
	}

	public String getTimuDaan()
	{
		return this.timuDaan;
	}

	public void setTimuDaan(String timuDaan)
	{
		this.timuDaan = timuDaan;
	}


	public Integer getKechengId()
	{
		return kechengId;
	}


	public void setKechengId(Integer kechengId)
	{
		this.kechengId = kechengId;
	}


	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}


	public Integer getTimuNandu() {
		return timuNandu;
	}


	public void setTimuNandu(Integer timuNandu) {
		this.timuNandu = timuNandu;
	}

}